# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['ai-layer/main.py'],
    pathex=['ai-layer'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.ciphers.aead',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.kdf',
        'numpy',
        'sqlite3',
        'multipart',
        'python_multipart',
        'websockets',
        'wsproto',
        'zeroconf',
        'ifaddr',
        'httpx',
        'aiosqlite',
        'fastapi',
        'uvicorn',
        'pydantic',
        'myca',
        'myca.api',
        'myca.node',
        'myca.crypto',
        'myca.discovery',
        'myca.connection',
        'myca.orchestrator',
        'myca.library',
        'myca.library.embedding',
        'myca.library.indexer',
        'myca.network_scanner',
        'myca.inference.backends.zgcompute',
        'myca.automation.scheduler',
        'myca.automation.api'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='myca-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
